# Generated by Django 3.2.19 on 2023-07-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=20)),
                ('productPrice', models.IntegerField()),
                ('productImage', models.ImageField(upload_to='')),
                ('productTemp', models.BooleanField(default=True)),
                ('productCategory', models.CharField(max_length=10)),
            ],
        ),
    ]
