# Generated by Django 3.2.18 on 2023-07-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productCategory',
        ),
    ]
