# Generated by Django 3.2.20 on 2023-07-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productTemp',
            field=models.CharField(max_length=10),
        ),
    ]
