# Generated by Django 3.2.20 on 2023-07-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartProduct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cartProductTemp',
        ),
    ]
