# Generated by Django 3.2.20 on 2023-07-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartTotalPrice',
            field=models.IntegerField(default=None),
        ),
    ]
