# Generated by Django 3.2.18 on 2023-07-03 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartProduct', '0001_initial'),
        ('orderProduct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='count',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='cart_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cartProduct.cartproduct'),
            preserve_default=False,
        ),
    ]
