# Generated by Django 3.2.20 on 2023-07-03 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20230703_1942'),
        ('cartProduct', '0002_remove_cartproduct_cartproducttemp'),
        ('orderProduct', '0002_auto_20230703_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='cart_product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cartProduct.cartproduct'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
